import {NavLink, useMatch} from "react-router-dom";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faChevronUp, faHouse} from "@fortawesome/free-solid-svg-icons";
import CategoriesNavigation from "./CategoriesNavigation";
import AuthorsNavigation from "./AuthorsNavigation";

const Footer = () => {
    const match = !useMatch("/");
    return (
        <footer className="py-4 mt-2 mt-md-3 bg-body border-top shadow w-100 align-self-end">
            <div className="container">
                <div className="row gy-2">
                    <div className="col-12 col-md-6 d-flex justify-content-center justify-content-md-start">
                        <span className="text-muted">Miscellaneous Stories generated by AI</span>
                    </div>
                    <div className="col-12 col-md-3 d-flex justify-content-center justify-content-md-end">
                        <div className="d-none d-md-inline-flex gap-4">
                            {match &&
                                <NavLink to="/" className="text-muted text-decoration-none">
                                    <FontAwesomeIcon icon={faHouse}/> home
                                </NavLink>
                            }
                            <a href="#" className="text-muted text-decoration-none">
                                <FontAwesomeIcon icon={faChevronUp}/> top
                            </a>
                        </div>
                        <div className="d-inline-flex d-md-none gap-4 fs-4">
                            {match &&
                                <NavLink to="/" className="text-muted text-decoration-none">
                                    <FontAwesomeIcon icon={faHouse}/> home
                                </NavLink>
                            }
                            <a href="#" className="text-muted text-decoration-none">
                                <FontAwesomeIcon icon={faChevronUp}/> top
                            </a>
                        </div>
                    </div>
                </div>
                <nav className="row gy-2 my-3 gx-5 d-sm-block d-md-none fs-5">
                    <div className="col-12 col-md-3">
                        <CategoriesNavigation/>
                    </div>
                    <div className="col-12 col-md-3">
                        <AuthorsNavigation/>
                    </div>
                </nav>
            </div>
        </footer>
    );
}

export default Footer;