import {useEffect, useState} from "react";
import {Helmet, HelmetProvider} from "react-helmet-async";
import {AppNavigationContext} from "../contexts";
import {useAuthors, useCategories} from "../hooks";
import Header from "./Header";
import Footer from "./Footer";
import MainPanel from "./MainPanel";
import ScrollToTop from "./ScrollToTop";

const Layout = () => {
    const {categories} = useCategories();
    const {authors} = useAuthors();
    const [state, setState] = useState();

    useEffect(() => {
        if (!categories) return;
        setState(s => ({
            ...s,
            categories: [...categories],
        }))
    }, [categories]);

    useEffect(() => {
        if (!authors) return;
        setState(s => ({
            ...s,
            authors: [...authors]
        }))
    }, [authors]);

    return (
        <HelmetProvider>
            <AppNavigationContext.Provider value={state}>
                <ScrollToTop>
                    <Helmet>
                        <title>{import.meta.env.VITE_SITE_NAME}: Miscellaneous Stories generated by AI</title>
                        <link rel="canonical" href={import.meta.env.VITE_CANONICAL_LINK}/>
                        <meta name="description" content="Miscellaneous Stories generated by AI"/>
                    </Helmet>
                    <Header/>
                    <MainPanel/>
                    <Footer/>
                </ScrollToTop>
            </AppNavigationContext.Provider>
        </HelmetProvider>
    )
}

export default Layout;